# Generated by Django 4.0.3 on 2023-09-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0005_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='salesperson',
        ),
    ]
