# Generated by Django 4.0.3 on 2023-09-06 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0006_remove_sale_customer_remove_sale_salesperson'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sales_rest.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='salesperson',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sales_rest.salesperson'),
        ),
    ]
