# Generated by Django 4.0.3 on 2023-09-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='vip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
